### ISSUE TITLE
Question: Is it possible to self host the script ?

### ISSUE THREAD

**Issue by ProTechEx** [efkann/pssh-extractor#1]
Hey mate,

is it possbile to self host the script, if yes how, as it doesn't contain a index html or php

**Comment by efkann** [comment]
I won't be sharing it as an external script, however you can see the logic and how it's implemented at [https://github.com/efkann/pssh-extractor/blob/main/src/utils.ts#L16](https://github.com/efkann/pssh-extractor/blob/main/src/utils.ts#L16)
